### PR TITLE
docs: Update, add workflow section

### PR DESCRIPTION
**Pull request by damianfedeczko**
Updated the documentation (typos etc), added a section about the tasks sequence which need to be performed by the Cloud Function in order to update the Dynamic Address Group in Panorama.

Please feel free to update it, ask questions if something is not clear or request a more verbose description if needed - will update accordingly to my knowledge.

Still one piece missing from my perspective:
- what data type we want to push to the Datastore and later on to Panorama, names, IPs, labels and/or network labels?
- what are the filter criteria for the VMs? Associated service account name?

### CODE REVIEW

**Comment by thedevilsvoice** [comment]
here are some notes from the customer
```
As we discussed on Friday’s meeting, there is a need to have the GCP cloud function query the predefined  “Google Service Account” tag in addition to all the Tags and labels assigned to VMs in GCP. The Service Account will allow to easily associate a particular application/project VM instances. The idea to have the Cloud function query all these tags and relay them to the Onprem Panorama that will use them in Dynamic Address Groups.

An example for a SA for the project XXXXXXX dev environment:

sa-proj-build@XXXXXXXX.iam.gserviceaccount.com

The following screenshot is the initial setup for the GCP plugin that we were testing with xxxxxx.  It shows the Notify Group that is used to identify the list different type of tags to pull from GCP.

    Predefined Tags that pulls the GCP resources including the “Google Service Account”              
    Identify all IPs assigned to a project/Application
    User Tags would allow to pull the GCP Labels (up to 16)                                                                         
    Network Tags would allow to pull the GCP Network Tags (up to 8)
```

**Review by thedevilsvoice — APPROVED** [review]
LGTM

**Comment by damianfedeczko** [comment]
@thedevilsvoice so it seems like the customer doesn't want to filter the Virtual Machines, but do a data exfiltration on all of them?

**Comment by thedevilsvoice** [comment]
> @thedevilsvoice so it seems like the customer doesn't want to filter the Virtual Machines, but do a data exfiltration on all of them?

That is my understanding. I think if we [focus on creating the functions described here](https://github.com/thedevilsvoice/gcp_tagging_automation/tree/main/docs#plan) we will be getting close to the finish line.

**Pull request merged**
